config/routes.rb
Rails.application.routes.draw do
  root to: 'links#index'

  resources :links, only: [:index, :create]
  get '/links/:url', to: 'links#show', as: 'link'
  resources :visits, only: [:index]
  get '/statistics', to: 'visits#stats'

  get '/:url', to: 'links#visit', as: 'redirect'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :visits

  validates_presence_of :original

  before_create :set_short
  after_create :create_cache_key

  def self.find_shorten!(short_url)
    Rails.cache.fetch(short_url) { Link.find_by_short!(short_url) }
  end

  private

  def set_short
    self.short = generate_short
  end

  def generate_short
    loop do
      short_url = SecureRandom::base58(8)
      break short_url unless Link.where(short: short_url).exists?
    end
  end

  def create_cache_key
    Rails.cache.write(short, self)
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :link

  scope :by_country, -> { group(:location) }
  scope :by_link, -> { joins(:link).group('links.original') }

  scope :last_n_with_links, -> (n) { includes(:link).last(n).reverse }

  def self.most_popular(number=10)
    order(count_id: :desc).limit(number).count(:id)
  end

  def self.cache_last_n_records(n)
    Rails.cache.write("last_#{n}", last_n_with_links(n))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :find_link, only: [:show, :visit]

  def index
    @link = Link.new
  end

  def show
  end

  def create
    @link = Link.new(link_params)

    if @link.save
      redirect_to link_path(@link.short), notice: 'Link was successfully created.'
    else
      render :index
    end
  end

  def visit
    visit = Visit.create!(ip: request.remote_ip, link: @link)
    GeoWorker.perform_async(visit.id, 3)

    redirect_to @link.original
  end

  private
    def find_link
      @link = Link.find_shorten!(params[:url])
    end

    def link_params
      params.require(:link).permit(:short, :original)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def index
    @visits = Rails.cache.fetch(:last_100, expires_in: 10.minutes) { Visit.last_n_with_links(100) }
  end

  def stats
    @total_visits = Visit.count
    @uniq_visits = Visit.distinct.pluck(:link_id).count
    @top_countries = Visit.by_country.most_popular
    @top_links = Visit.by_link.most_popular
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def toggle_active(path)
    request.path == path ? 'active' : ''
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | UrlShortener
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      .container
        nav.navbar.navbar-expand-lg.navbar-light.bg-light
          = link_to 'Shorten It!', root_path, class: 'navbar-brand'
          .navbar.font-italic.text-secondary Simple & Fast Way to make URLs short!
          button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"]
            span.navbar-toggler-icon
          #navbarNavDropdown.collapse.navbar-collapse.justify-content-end
            ul.navbar-nav
              li.nav-item class=toggle_active(root_path)
                = link_to 'Home', root_path, class: 'nav-link'
              li.nav-item class=toggle_active(visits_path)
                = link_to 'Visits', visits_path, class: 'nav-link'
              li.nav-item class=toggle_active(statistics_path)
                = link_to 'Statistics', statistics_path, class: 'nav-link'
      .container= yield

app/views/links/index.html.slim
.container
  p
    .col-md-8.offset-md-2
      = form_with(model: @link, local: true, class: 'justify-content-center input-group') do |form|
        = form.text_field :original, placeholder: 'Enter URL you want to shorten...', class: 'form-control'
        - if @link.errors.any?
          .help-block.text-left= @link.errors.full_messages.first

        .form-group
          .actions
            = form.submit 'Get the Link!', class: 'btn btn-info'

app/views/links/show.html.slim
.container
  p
    .col-md-8.offset-md-2
      .justify-content-center.input-group
        = text_field_tag :short, "#{request.base_url}/#{@link.short}", class: 'form-control', readonly: true
        = link_to 'Shorten More!', links_path, class: 'btn btn-info'

app/views/visits/_stat.html.slim
tr
  td= stat.first
  td= stat.second

app/views/visits/index.html.slim
table.table.table-hover
  tr
    th URL
    th IP
    th Location
    th When Visited
  - @visits.each do |visit|
    tr
      td= link_to redirect_path(visit.link.short)
      td= visit.ip
      td= visit.location
      td= visit.created_at.getlocal.to_s(:short)

app/views/visits/stats.html.slim
.container
  .row.col-md-6
  p.lead.text-muted #{@total_visits} total | #{@uniq_visits} uniq visits
  .row
    .col-md-6
      h4.text-info TOP 10 Countries
      table.table.table-condensed
        tr
          th Location
          th Visits
        = render partial: 'stat', collection: @top_countries, as: :stat

    .col-md-6
      h4.text-info 10 Most Visited Links
      table.table.table-condensed
        tr
          th Link
          th Visits
        = render partial: 'stat', collection: @top_links, as: :stat